---
title: "In the media"
output: html_document
---
**************

### Interviews and Quotations by the Media

- Risk.net, "[Asia RBC reforms push insurers to rethink investment strategies](https://www.risk.net/asset-management/insurance/2370949/asia-rbc-reforms-push-insurers-rethink-investment-strategies)". 2014 Sept.
		
- The Wall Street Journal, "[Insurers in Taiwan Pay the Price for Misjudging Covid Risks](https://www.wsj.com/articles/insurers-in-taiwan-pay-the-price-for-misjudging-covid-risks-11655546402?st=pq2gfe624vsig6a&reflink=desktopwebshare_permalink)". 2022 June
		
- Muma College of Business News, "[Pensionable overtime raises pension costs by almost 20\%, study finds](https://www.usf.edu/business/news/2022/08-08-pensionable-overtime-study.aspx)". 2022 Aug.

- The PLoS One paper has been attracting very interesting media attention. Please find a small selection below. A more complete list can be found [here](https://plos.altmetric.com/details/144590859/news).
    - BBC Newsround, "[More happy birthdays! Research says people could live to 141](https://www.bbc.co.uk/newsround/65121184)", 2023 March.

    - Fortune, "[There may not be a limit on how long humans can live—and if there is, experts say 'we are not yet approaching it'](https://fortune.com/well/2023/03/31/how-long-can-humans-live-limit/)", 2023 March.

    - New Scientist, "[How long can humans live? We may not have hit the limit yet](https://www.newscientist.com/article/2366876-how-long-can-humans-live-we-may-not-have-hit-the-limit-yet/)", 2023 March.

    - The Telegraph, "[Are you a man born in 1970? You might live to be 141](https://www.telegraph.co.uk/news/2023/03/29/life-expectancy-man-born-in-1970-could-live-to-141/)", 2023 March.

    - UGA News, Terry News, "[Study suggests we haven't reached the maximum human lifespan](https://www.terry.uga.edu/news/stories/2023/study-suggests-we-havent-reached-maximum-human-lifespan)", 2023 March

    - Daily Mail, "[Humans alive now could reach 140, scientists predict - as they say we're nowhere near 'maximum' lifespan yet](https://www.dailymail.co.uk/health/article-11916689/Humans-alive-reach-140-scientists-predict-near-maximum-lifespan.html)", 2023 March.

    - USF Muma College of Business, "[Po-Lin Wang | Longevity Research | Baldwin Risk Partners School of Risk Management and Insurance](https://www.youtube.com/watch?v=qnqb2TbNLk8)", 2023 May.

    - Business Insider, "[Humans may not have reached a maximum lifespan yet — people could soon live to 120 and beyond](https://www.insider.com/maximum-human-age-scientists-think-up-for-debate-2023-3?_gl=1*1qltdha*_ga*MTEwMDgyNjQwNy4xNjgwMTE0NDg1*_ga_E21CV80ZCZ*MTY4MDExNDQ4NC4xLjEuMTY4MDExNDU1My41MS4wLjA)", 2023 March

    - Live Science, "[We're nowhere near reaching the maximum human life span, controversial study suggests](https://www.livescience.com/were-nowhere-near-reaching-the-maximum-human-life-span-controversial-study-suggests)", 2023 March.

    - CNN Indonesia, "[Studi Ungkap 40 Tahun Mendatang Usia Manusia Bisa Lebih Panjang](https://www.cnnindonesia.com/teknologi/20230403095420-199-932729/studi-ungkap-40-tahun-mendatang-usia-manusia-bisa-lebih-panjang), 2023 April

    - Yahoo, "[Humans Will Break the Longevity Record and Live Past 122, Study Says](https://www.yahoo.com/lifestyle/humans-break-longevity-record-live-200600724.html?guccounter=1&guce_referrer=aHR0cHM6Ly9wbG9zLmFsdG1ldHJpYy5jb20vZGV0YWlscy8xNDQ1OTA4NTkvbmV3cw&guce_referrer_sig=AQAAAI119vciy6z1uwrknTEacta_Yi6Epvdih3l7o75rW0Q2hQM4YZuPTG4jrZFlk5VCvv7EF7dJ3PJH6q4D0P--TWnjeARTHKP8yLd_W7jFDGR3kQ74DVak1Ozzas1iyAcQtuscbN113IfPaUUlWvvkJ_EIDmcSUaLWMKsens-uBYIX)", 2023 April.

    - MSN Korea, "[세계 최고령 122살 곧 깨진다…"40년 안 걸려"](https://www.msn.com/ko-kr/news/techandscience/122%EC%82%B4-%EC%B5%9C%EA%B3%A0-%EC%88%98%EB%AA%85-%EA%B8%B0%EB%A1%9D%EC%9D%80-%EC%96%B8%EC%A0%9C-%EA%B9%A8%EC%A7%88%EA%B9%8C/ar-AA1aI0vv)", 2023 May